### ISSUE TITLE
create home page 

### ISSUE THREAD

**Issue by Rohit-554** [Rohit-554/Fud#5]
The Home page will : 

- Fetch the api data from the Food api as mentioned in the readme 
- Show all the recipes in it

**Comment by Saumya-28** [comment]
Please assign me this issue.

**Comment by Harshsharmaa28** [comment]
@Rohit-554 if intreseted i can work for you for building whole website

**Comment by Rohit-554** [comment]
> @Rohit-554 if intreseted i can work for you for building whole website

Sorry @Harshsharmaa28 , but this is a flutter project and we are targeting phone

**Comment by Harshsharmaa28** [comment]
@Rohit-554 oh that's fine

**Comment by Rohit-554** [comment]
Thanks
